### ISSUE TITLE
flptd2root.py segmentation violation

### ISSUE THREAD

**Issue by lecdawson** [SuperNEMO-DBD/PTD2Root#2]
Hi,
I have been trying to run flptd2root.py on reconstructed files that include gamma tracking. This should be possible as Cheryl has successfully run the code on her mac. I have recently upgraded falaise but I get the following error when I run the script:

Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
Missing FileEntry for /tmp/bayeux-20170509-83837-laq70k/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
Missing FileEntry for /tmp/bayeux-20170509-83837-laq70k/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
requested to autoload type brio_record
Warning in TStreamerInfo::BuildCheck:
The StreamerInfo of class TArrayCMod read from file Tl208_1M_flrec2_1.brio
has the same version (=1) as the active class but a different checksum.
You should update the version to ClassDef(TArrayCMod,2).
Do not try to write objects with the current class definition,
the files will not be readable.

Warning in TStreamerInfo::CompareContent: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from
the on-file layout version 1:
char* fArray; //
Warning in TStreamerInfo::CompareContent: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from
the on-file layout version 1:
int fCapacity; //
[notice:void datatools::library_loader::init():450] Automatic loading of library 'PTD2Root'...

*** Break *** segmentation violation
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

Any suggestions as to how I can fix this issue?

**Comment by cherylepatrick** [comment]
Note: I tried running ptd2root on my Mac, on the same files (both with and without gamma tracking) as Lauren, and it worked for me. So I don't think the input files are the problem.

**Comment by yramachers** [comment]
I just tried it on a reconstructed Falaise2.0 brio file, i.e. containing the PTD data bank and I get the same error:
--------------------------------------------------------------
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170621-24414-n9va8u/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /tmp/bayeux-20170621-24414-n9va8u/Bayeux-3.0.0/source/bxbrio/include/brio/detail/brio_record.h
   requested to autoload type brio_record
Warning in <TStreamerInfo::BuildCheck>: 
   The StreamerInfo of class TArrayCMod read from file e1MeV_1000_ptd.brio
   has the same version (=1) as the active class but a different checksum.
   You should update the version to ClassDef(TArrayCMod,2).
   Do not try to write objects with the current class definition,
   the files will not be readable.

Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from 
the on-file layout version 1:
   char* fArray; //
Warning in <TStreamerInfo::CompareContent>: The following data member of
the in-memory layout version 1 of class 'TArrayCMod' is missing from 
the on-file layout version 1:
   int fCapacity; //
terminate called after throwing an instance of 'std::logic_error'
  what():  [void FLReconstruct::do_postprocess(FLReconstruct::FLReconstructParams&):445: Missing services configuration file!]
Abort
-------------------

Then I run exactly the same module on a reconstructed Falaise3.0 file and all works. Note that the Falaise2.0 file I used was created in 2015 and back then the conversion to ROOT still worked since I got both files in my folder. Something appears to have changed in Falaise3.0, rendering the use of version 2.0 files somewhat unstable.

**Comment by cherylepatrick** [comment]
Same here - I couldn't run it on Falaise 2 files either, but it was fine on Falaise 3 files (and the files Lauren was trying were Falaise 3).

**Comment by lecdawson** [comment]
I have noticed a difference in myself and Cheryl's p2r.conf files. The directory for ptd2root looks in CadfaelBrew/Cellar/ptd2root/0.1.0/lib c.f. CadfaelBrew/Cellar/ptd2root/1.0.0/lib in Cheryl's. Not sure how we have different versions when I have updated and upgrade Falaise recently.

**Comment by cherylepatrick** [comment]
I had to do a complete uninstall/reinstall of all the Cadfael stuff to get from falaise 2 to 3 (shudder) so it might be that the upgrade process doesn't pick this up - maybe try to uninstall/reinstall ptd2root using brew?

**Comment by lecdawson** [comment]
I have run 'brew unlink ptd2root' and I'm now running 'brew install ptd2root'. Will update on here when it has finished.

**Comment by lecdawson** [comment]
Reinstalling ptd2root and ensuring I was using version 1.0.0 has worked.
